### ISSUE TITLE
Feed names with whitespace, do not get uploaded to remote.

### ISSUE THREAD

**Issue by k-quigley** [emoncms/sync#28]
Our setup is running from an emoncms (running on Pi - using pre-built SD card), configured to sync to a remote, self-hosted online emoncms. 

We have managed to connect the two services together - and we can see the local and remote feeds in the list.   Feeds can be uploaded to the remote, online emoncms and we see data.

If a feed name contains any white-space; the feed fails to upload.  The "Local ahead of Remote by xxx" counter slowly increments.

**Comment by TrystanLea** [comment]
Thanks @k-quigley I've added just the urlencode change in here, there where quite a few white space changes in your pull request and I prefer to keep changes to a minimum https://github.com/emoncms/sync/commit/a18125e8e61ef0990e634cb57b5aa90a2b4a63f2
