### ISSUE TITLE
Credentials not URL encoded

### ISSUE THREAD

**Issue by SeanDS** [emoncms/sync#5]
The remote username and password are not sanitised or encoded for posting via URL. I think this is causing the issue I am experiencing, which is that authentication fails against my remote server. My password is full of special characters that need encoded for POSTing.

According to the [PHP documentation](https://secure.php.net/manual/en/function.curl-setopt.php) for `curl_setopt`'s `CURLOPT_POSTFIELDS` setting, this post data must be URL encoded.

In general there are other places that should use encoding, e.g. [here](https://github.com/emoncms/sync/blob/67a12d6ff1da70a9d3a6432f0688d60a82ec71a8/lib/phpfina.php#L152). Basically it should be used everywhere regardless of whether the data is expected to be safe or not.

**Comment by glynhudson** [comment]
Fixed https://github.com/emoncms/sync/issues/11
