### ISSUE TITLE
PHP 7.3 issue with hyphen on regular expression

### ISSUE THREAD

**Issue by thekazak** [emoncms/sync#8]
Hi,
there is an issue with PHP7.3 and hyphen in regex
check https://github.com/emoncms/emoncms/issues/1180 for reference

[sync.diff.txt](https://github.com/emoncms/sync/files/2955727/sync.diff.txt)

**Comment by reedy** [comment]
@thekazak Want to submit this as a proper PR? :)

**Comment by reedy** [comment]
https://github.com/emoncms/sync/blob/master/sync-module/sync_model.php#L47

Task can be closed?
